# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8f2872dc6df9db435531e2497301b8de905dd4be9ce89184c2a75ae57ec6a0eb74cca1e53463ba632e99e4ac2a668974b26356e1a2dadb785535562f510e1d5

test:
  secret_key_base: 379e8d20ff93d1f9a285e84c67b78c9be615a9d14fe5e30f8b9286bc158b76508579560f5df9ef413e618b9e0939ed5035d13a6a25e21b96ab672d261388fb16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
